### ISSUE TITLE
release version can not run in windows?

### ISSUE THREAD

**Issue by winds2016** [pions/turn#16] opened 2018-05-12 12:32 UTC
Can not run direct version AMD64. there have not params like USERS.
Maybe config file is better?

**Comment by Sean-Der** [comment] 2018-05-13 06:25
Hi @winds2016 

Thanks for using Pion! I set my environment vars in powershell by doing
```
$env:USERS = "user=password"
$env:REALM = "localhost"
$env:UDP_PORT = 3478
```
We might do a config file eventually, but that would make some people happy (and other annoyed)
By doing environment variables we allow people to use anything (they can write a script that reads a file and then sets them. 

I did hit a bug though when using it, are you able to launch on Windows? I am going to investigate this now, using Windows Server 2016 Datacenter on AWS.
```
PS C:\Users\Administrator\go\src\github.com\pions\turn> go run .\cmd\simple-turn.go
not supported by windows
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
github.com/pions/turn.Start(0x5600a0, 0x617e80, 0xc04200c4a0, 0xf, 0xd96)
        C:/Users/Administrator/go/src/github.com/pions/turn/turn.go:31 +0xe1
main.main()
        C:/Users/Administrator/go/src/github.com/pions/turn/cmd/simple-turn.go:48 +0x2fa
exit status 2
```

**Comment by Sean-Der** [comment] 2018-05-13 06:43
Hey @winds2016 so the issue is that Golang on Windows is missing, https://go-review.googlesource.com/c/net/+/76394

I will work on getting that merged in!

**Comment by winds2016** [comment] 2018-05-13 09:51
I have same error in win7 64bit
Waiting for your update,i can not visit the URL:(

**Comment by tmm1** [comment] 2018-05-13 18:52
@Sean-Der can you try go1.11 (specifically https://github.com/golang/go/commit/d2c7dec183f0da628abf16848e9e92987feebe32) with https://github.com/golang/net/compare/master...fancybits:fancybits to see how it works for your use-case?

**Comment by Sean-Der** [comment] 2018-05-14 05:28
@tmm1 Thanks for that!

This is awesome, got exactly what I needed. I did hit another bug (but was able to work around it) if I use `:80` instead of udp4 + `0.0.0.0:80` when listening I would have the following error

```
err: write udp [::]:50147->172.31.22.172:50149: sendmsg: The system detected an invalid pointer address in attempting to use a pointer argument in a call.
```
---
@winds2016 Can you try the 1.0.1 release? It works for me on Windows 2016, I turned off the firewall and set the env variables in Powershell like I showed above, and it works!

**Comment by winds2016** [comment] 2018-05-14 07:26
@Sean-Der 
It run success!
But:
1、When i build it myself,it show error: Failed to SetControlMessage ipv4.FlagDst: not suported by windows;
2、When i test with turnutils_uclient,it show error 400(Bad Request: The request was malformed);
simple-turn info:Failed to handle ALLOCATE-REQUEST from <client ip:port>:MessageIntegrity mismatch be972cf1e52c24d839534e1999dd45f1a 4c79...
and so WEBRTC

**Comment by Sean-Der** [comment] 2018-05-14 16:28
Fantastic! So for those two issues 

1.) You will need to build Golang from git. https://github.com/pions/turn/issues/16#issuecomment-388647865 Where the changes I needed

2.) That means bad auth username/password/realm must differ (or that method is broken) I will download that utility you mentioned. I have only tested Chromium so far.

**Comment by tmm1** [comment] 2018-05-14 16:33
> I did hit another bug (but was able to work around it) if I use :80 instead of udp4 + 0.0.0.0:80

Strange, would be good to get to the bottom of this. Is it happening in the ipv6 code? Can you trigger if you use `udp4 + :80`, or `udp6 + 0.0.0.0:80`?

**Comment by Sean-Der** [comment] 2018-05-14 18:30
@tmm1 

I will work on getting a simple reproduce tonight, it should be easy enough. All the inbound/outbound traffic  was ipv4, but I have no idea about the code paths. thanks!

**Comment by Sean-Der** [comment] 2018-05-15 05:17
Hey @winds2016 

I checked it out, and coturnd client requires reservation-token and even-port, we currently don't support either. What client are you using? What are you testing/asserting with turnutils_uclient?

I am hesitant to add these things before TCP, those things are actively stopping people from using `pion-turn` but if they block you I can add them in the next day or two!

**Comment by winds2016** [comment] 2018-05-15 08:34
@Sean-Der 
I want to use in WEBRTC.Turnutils_uclient just is used to test TURN server only,I can use other test client.

There is same error info from simple_turn when i use it in WEBRTC,my client is firefox, and firefox say TURN server maybe brocked.
But i'm not sure whether my WEBRTC config is right,so i want to test with simple enough client.

I will check in chrome.

**Comment by winds2016** [comment] 2018-05-16 06:56
Thank you for this project and immediate processing.There are some bugs always for any software:)

I'm sorry too.I build failed for golang latest version,and can not visit golang.org/wl.Do you know other download url for go install program windows latest version?thanks!

**Comment by Sean-Der** [comment] 2018-05-16 08:12
@winds2016 

Hey! Mind trying the new release, it works with `turnutils_uclient` now (and Chrome should still work also)

Auth works, but the actual benchmarking doesn't return useful data. I am going to work with coturnd, don't fully understand what is at fault yet.

**Comment by Sean-Der** [comment] 2018-05-16 08:47
Created mailing list thread https://groups.google.com/forum/#!topic/turn-server-project-rfc5766-turn-server/ij-35rPUxRk

**Comment by winds2016** [comment] 2018-05-16 09:13
@Sean-Der 
I test:
Chrome is OK
Firefox and turnutils_uclient fails, simple-turn show: unable to handle ChannelData from <ip:port>: failed writing to socket: write udp 0.0.0.0:58461->0.0.0.0:3480: sendmsg: The requested address is not valid in its context

Client can't recv data from server

**Comment by Sean-Der** [comment] 2018-05-16 17:32
Thanks again for testing!

Are you ok with me opening tickets for FireFox + uclient separately and closing this one, I believe everything works well with Windows now? That way when I close them they are all in one place.

I think they will both be fixed fairly quickly, but when people look around they will only see this ticket (and not see conversation/commits around those topics)

thanks!

**Comment by Sean-Der** [comment] 2018-05-17 07:44
Closing since we work with Windows now, created #19 and #20 to track.

If you arrived at this issue from search engine see https://github.com/pions/turn/issues/16#issuecomment-388647865 for what you need to work on Windows

**Closed by Sean-Der** 2018-05-17 07:44 UTC
Labels: bug

**Comment by winds2016** [comment] 2018-05-18 02:11
Ok, i think so too
